version: '3.8'

services:
  blog-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - POSTGRES_HOST=postgres-blog
      - POSTGRES_PORT=5432
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret_key
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=blog-events
    depends_on:
      - postgres-blog
      - redis
      - kafka
    networks:
      - app-network

  postgres-blog:
    image: postgres:14
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog_db
    volumes:
      - postgres-blog-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-blog-data: